version: '3.8'

services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_post_publisher
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Madrid
    networks:
      - publisher_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  publisher_network:
    driver: bridge
